### ISSUE TITLE
Support configurable health checks

### ISSUE THREAD

**Issue by autodidaddict** [wascc/nats-provider#5]
The NATS provider should offer an opt-in health check mechanism. If this feature is enabled, then the provider will perform health checks on bound actors on a configured interval. After a configurable number of health check failures, the provider will explicitly unbind/deconfigure the failing actor.

This feature is largely in support of lattice mode.

**Comment by ewbankkit** [comment]
I assume that this health-check mechanism would be available to all capability providers? It seems like it would be applicable to a large variety of providers.

**Comment by autodidaddict** [comment]
the health check mechanism is already available - if a provider dispatches the `OP_HEALTH_CHECK` message to any of its bound actors, they will get either an `Ok` or an `Err` back. It's just that none of the providers (except the one in the `wasmdome` engine) actually send this message.
